version: "3"
services:
  trip-quota-php:
    build: ./docker
    container_name: trip-quota-app
    # traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=degg-develop-net
      - traefik.http.routers.myisbn-app.rule=Host(`trip-quota.degg`)
    volumes:
      - .:/var/www
    networks:
      - degg-develop-net
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=degg-mysql
      - DB_PORT=3306
      - DB_USERNAME=${DB_USER:-homestead}
      - DB_PASSWORD=${DB_PASS:-secret}
      - MAIL_HOST=degg-mailhog
      - MULTI_MAIL_HOST=degg-mailhog
networks:
  degg-develop-net:
    external: true
