<?php

namespace App\Enums;

enum TimezoneEnum: string
{
    case AFRICA_ABIDJAN = 'Africa/Abidjan';
    case AFRICA_ALGIERS = 'Africa/Algiers';
    case AFRICA_BISSAU = 'Africa/Bissau';
    case AFRICA_CAIRO = 'Africa/Cairo';
    case AFRICA_CASABLANCA = 'Africa/Casablanca';
    case AFRICA_CEUTA = 'Africa/Ceuta';
    case AFRICA_EL_AAIUN = 'Africa/El_Aaiun';
    case AFRICA_JOHANNESBURG = 'Africa/Johannesburg';
    case AFRICA_JUBA = 'Africa/Juba';
    case AFRICA_KHARTOUM = 'Africa/Khartoum';
    case AFRICA_LAGOS = 'Africa/Lagos';
    case AFRICA_LIBREVILLE = 'Africa/Libreville';
    case AFRICA_MAPUTO = 'Africa/Maputo';
    case AFRICA_MONROVIA = 'Africa/Monrovia';
    case AFRICA_NAIROBI = 'Africa/Nairobi';
    case AFRICA_NDJAMENA = 'Africa/Ndjamena';
    case AFRICA_NOUAKCHOTT = 'Africa/Nouakchott';
    case AFRICA_SAO_TOME = 'Africa/Sao_Tome';
    case AFRICA_TRIPOLI = 'Africa/Tripoli';
    case AFRICA_TUNIS = 'Africa/Tunis';
    case AFRICA_WINDHOEK = 'Africa/Windhoek';
    case AMERICA_ADAK = 'America/Adak';
    case AMERICA_ANCHORAGE = 'America/Anchorage';
    case AMERICA_ANGUILLA = 'America/Anguilla';
    case AMERICA_ANTIGUA = 'America/Antigua';
    case AMERICA_ARAGUAINA = 'America/Araguaina';
    case AMERICA_ARUBA = 'America/Aruba';
    case AMERICA_ASUNCION = 'America/Asuncion';
    case AMERICA_ATIKOKAN = 'America/Atikokan';
    case AMERICA_BAHIA = 'America/Bahia';
    case AMERICA_BAHIA_BANDERAS = 'America/Bahia_Banderas';
    case AMERICA_BARBADOS = 'America/Barbados';
    case AMERICA_BELEM = 'America/Belem';
    case AMERICA_BELIZE = 'America/Belize';
    case AMERICA_BOA_VISTA = 'America/Boa_Vista';
    case AMERICA_BOGOTA = 'America/Bogota';
    case AMERICA_BOISE = 'America/Boise';
    case AMERICA_CAMBRIDGE_BAY = 'America/Cambridge_Bay';
    case AMERICA_CAMPO_GRANDE = 'America/Campo_Grande';
    case AMERICA_CANCUN = 'America/Cancun';
    case AMERICA_CARACAS = 'America/Caracas';
    case AMERICA_CAYMAN = 'America/Cayman';
    case AMERICA_CHICAGO = 'America/Chicago';
    case AMERICA_CHIHUAHUA = 'America/Chihuahua';
    case AMERICA_COMODORO_RIVADAVIA = 'America/Comodoro_Rivadavia';
    case AMERICA_COSTA_RICA = 'America/Costa_Rica';
    case AMERICA_CRESTON = 'America/Creston';
    case AMERICA_CUIABA = 'America/Cuiaba';
    case AMERICA_CURACAO = 'America/Curacao';
    case AMERICA_DANVILLE = 'America/Danville';
    case AMERICA_DETROIT = 'America/Detroit';
    case AMERICA_DOMINICA = 'America/Dominica';
    case AMERICA_EDMONTON = 'America/Edmonton';
    case AMERICA_EIRUNEPE = 'America/Eirunepe';
    case AMERICA_EL_SALVADOR = 'America/El_Salvador';
    case AMERICA_FORTALEZA = 'America/Fortaleza';
    case AMERICA_GLACE_BAY = 'America/Glace_Bay';
    case AMERICA_GOOSE_BAY = 'America/Goose_Bay';
    case AMERICA_GRAND_TURK = 'America/Grand_Turk';
    case AMERICA_GRENADA = 'America/Grenada';
    case AMERICA_GUATEMALA = 'America/Guatemala';
    case AMERICA_GUAYAQUIL = 'America/Guayaquil';
    case AMERICA_GUYANA = 'America/Guyana';
    case AMERICA_HALIFAX = 'America/Halifax';
    case AMERICA_HAVANA = 'America/Havana';
    case AMERICA_HERMOSILLO = 'America/Hermosillo';
    case AMERICA_INDIANAPOLIS = 'America/Indianapolis';
    case AMERICA_INUVIK = 'America/Inuvik';
    case AMERICA_IQUITOS = 'America/Iquitos';
    case AMERICA_JAMAICA = 'America/Jamaica';
    case AMERICA_JUNEAU = 'America/Juneau';
    case AMERICA_KENTUCKY_LOUISVILLE = 'America/Kentucky/Louisville';
    case AMERICA_KRALENDIJK = 'America/Kralendijk';
    case AMERICA_LA_PAZ = 'America/La_Paz';
    case AMERICA_LIMA = 'America/Lima';
    case AMERICA_LOS_ANGELES = 'America/Los_Angeles';
    case AMERICA_LOWER_PRINCE = 'America/Lower_Prince';
    case AMERICA_MACEIO = 'America/Maceio';
    case AMERICA_MANAGUA = 'America/Managua';
    case AMERICA_MANAUS = 'America/Manaus';
    case AMERICA_MARIGOT = 'America/Marigot';
    case AMERICA_MARTINIQUE = 'America/Martinique';
    case AMERICA_MATAMOROS = 'America/Matamoros';
    case AMERICA_MAZATLAN = 'America/Mazatlan';
    case AMERICA_MENOMINEE = 'America/Menominee';
    case AMERICA_MERIDA = 'America/Merida';
    case AMERICA_METROPOLIS = 'America/Metropolis';
    case AMERICA_MEXICO_CITY = 'America/Mexico_City';
    case AMERICA_MIQUELON = 'America/Miquelon';
    case AMERICA_MONCTON = 'America/Moncton';
    case AMERICA_MONTEVIDEO = 'America/Montevideo';
    case AMERICA_MONTERREY = 'America/Monterrey';
    case AMERICA_MONTREAL = 'America/Montreal';
    case AMERICA_NASSAU = 'America/Nassau';
    case AMERICA_NEW_YORK = 'America/New_York';
    case AMERICA_NIPIGON = 'America/Nipigon';
    case AMERICA_NOME = 'America/Nome';
    case AMERICA_NORONHA = 'America/Noronha';
    case AMERICA_NORTH_DAKOTA_CENTER = 'America/North_Dakota/Center';
    case AMERICA_NORTH_DAKOTA_NEW_SALEM = 'America/North_Dakota/New_Salem';
    case AMERICA_NUUK = 'America/Nuuk';
    case AMERICA_OJINAGA = 'America/Ojinaga';
    case AMERICA_PANAMA = 'America/Panama';
    case AMERICA_PANGNIRTUNG = 'America/Pangnirtung';
    case AMERICA_PARAMARIBO = 'America/Paramaribo';
    case AMERICA_PHOENIX = 'America/Phoenix';
    case AMERICA_PORT_AU_PRINCE = 'America/Port-au-Prince';
    case AMERICA_PORT_OF_SPAIN = 'America/Port_of_Spain';
    case AMERICA_PORTO_VELHO = 'America/Porto_Velho';
    case AMERICA_PUERTO_RICO = 'America/Puerto_Rico';
    case AMERICA_PUNT_ARENAS = 'America/Punt_Arenas';
    case AMERICA_RAINY_RIVER = 'America/Rainy_River';
    case AMERICA_RECIFE = 'America/Recife';
    case AMERICA_REGINA = 'America/Regina';
    case AMERICA_RIO_BRANCO = 'America/Rio_Branco';
    case AMERICA_SANTIAGO = 'America/Santiago';
    case AMERICA_SANTO_DOMINGO = 'America/Santo_Domingo';
    case AMERICA_SAO_PAULO = 'America/Sao_Paulo';
    case AMERICA_SCORESBYSUND = 'America/Scoresbysund';
    case AMERICA_SHIPROCK = 'America/Shiprock';
    case AMERICA_SITKA = 'America/Sitka';
    case AMERICA_ST_BARTHELEMY = 'America/St_Barthelemy';
    case AMERICA_ST_JOHNS = 'America/St_Johns';
    case AMERICA_ST_KITTS = 'America/St_Kitts';
    case AMERICA_ST_LUCIA = 'America/St_Lucia';
    case AMERICA_ST_THOMAS = 'America/St_Thomas';
    case AMERICA_ST_VINCENT = 'America/St_Vincent';
    case AMERICA_SUDBURY = 'America/Sudbury';
    case AMERICA_SWIFT_CURRENT = 'America/Swift_Current';
    case AMERICA_TEGUCIGALPA = 'America/Tegucigalpa';
    case AMERICA_THULE = 'America/Thule';
    case AMERICA_THUNDER_BAY = 'America/Thunder_Bay';
    case AMERICA_TIJUANA = 'America/Tijuana';
    case AMERICA_TORONTO = 'America/Toronto';
    case AMERICA_TORTOLA = 'America/Tortola';
    case AMERICA_VANCOUVER = 'America/Vancouver';
    case AMERICA_WHITEHORSE = 'America/Whitehorse';
    case AMERICA_WINNIPEG = 'America/Winnipeg';
    case AMERICA_YAKUTAT = 'America/Yakutat';
    case AMERICA_YELLOWKNIFE = 'America/Yellowknife';
    case ANTARCTICA_CASEY = 'Antarctica/Casey';
    case ANTARCTICA_DAVIS = 'Antarctica/Davis';
    case ANTARCTICA_DUMONT_D_URVILLE = 'Antarctica/DumontDUrville';
    case ANTARCTICA_MACQUARIE = 'Antarctica/Macquarie';
    case ANTARCTICA_MAWSON = 'Antarctica/Mawson';
    case ANTARCTICA_PALMER = 'Antarctica/Palmer';
    case ANTARCTICA_ROTHERA = 'Antarctica/Rothera';
    case ANTARCTICA_SYOWA = 'Antarctica/Syowa';
    case ANTARCTICA_TROLL = 'Antarctica/Troll';
    case ANTARCTICA_VOSTOK = 'Antarctica/Vostok';
    case ARCTIC_LONGYEARBYEN = 'Arctic/Longyearbyen';
    case ASIA_ADEN = 'Asia/Aden';
    case ASIA_ALMATY = 'Asia/Almaty';
    case ASIA_AMMAN = 'Asia/Amman';
    case ASIA_ANADYR = 'Asia/Anadyr';
    case ASIA_AQTAU = 'Asia/Aqtau';
    case ASIA_AQTUBE = 'Asia/Aqtobe';
    case ASIA_ASHGABAT = 'Asia/Ashgabat';
    case ASIA_ATYRAU = 'Asia/Atyrau';
    case ASIA_BAGHDAD = 'Asia/Baghdad';
    case ASIA_BAKU = 'Asia/Baku';
    case ASIA_BANGKOK = 'Asia/Bangkok';
    case ASIA_BARNAUL = 'Asia/Barnaul';
    case ASIA_BEIRUT = 'Asia/Beirut';
    case ASIA_BISHKEK = 'Asia/Bishkek';
    case ASIA_BRUNEI = 'Asia/Brunei';
    case ASIA_CHITA = 'Asia/Chita';
    case ASIA_CHOIBALSAN = 'Asia/Choibalsan';
    case ASIA_COLOMBO = 'Asia/Colombo';
    case ASIA_DAMASCUS = 'Asia/Damascus';
    case ASIA_DHAKA = 'Asia/Dhaka';
    case ASIA_DILI = 'Asia/Dili';
    case ASIA_DUBAI = 'Asia/Dubai';
    case ASIA_DUSHANBE = 'Asia/Dushanbe';
    case ASIA_FAMAGUSTA = 'Asia/Famagusta';
    case ASIA_GANDHINAGAR = 'Asia/Gandhinagar';
    case ASIA_GAZA = 'Asia/Gaza';
    case ASIA_HEBRON = 'Asia/Hebron';
    case ASIA_HONG_KONG = 'Asia/Hong_Kong';
    case ASIA_HOVD = 'Asia/Hovd';
    case ASIA_IRKUTSK = 'Asia/Irkutsk';
    case ASIA_ISTANBUL = 'Asia/Istanbul';
    case ASIA_JAKARTA = 'Asia/Jakarta';
    case ASIA_JAYAPURA = 'Asia/Jayapura';
    case ASIA_JERUSALEM = 'Asia/Jerusalem';
    case ASIA_KABUL = 'Asia/Kabul';
    case ASIA_KAMCHATKA = 'Asia/Kamchatka';
    case ASIA_KARACHI = 'Asia/Karachi';
    case ASIA_KASHGAR = 'Asia/Kashgar';
    case ASIA_KATHMANDU = 'Asia/Kathmandu';
    case ASIA_KHANDYGA = 'Asia/Khandyga';
    case ASIA_KOLKATA = 'Asia/Kolkata';
    case ASIA_KRASNOYARSK = 'Asia/Krasnoyarsk';
    case ASIA_KUALA_LUMPUR = 'Asia/Kuala_Lumpur';
    case ASIA_KUCHING = 'Asia/Kuching';
    case ASIA_KUWAIT = 'Asia/Kuwait';
    case ASIA_MACAU = 'Asia/Macau';
    case ASIA_MAGADAN = 'Asia/Magadan';
    case ASIA_MAKASSAR = 'Asia/Makassar';
    case ASIA_MANILA = 'Asia/Manila';
    case ASIA_MUSCAT = 'Asia/Muscat';
    case ASIA_NICOSIA = 'Asia/Nicosia';
    case ASIA_NOVOKUZNETSK = 'Asia/Novokuznetsk';
    case ASIA_NOVOSIBIRSK = 'Asia/Novosibirsk';
    case ASIA_OMSK = 'Asia/Omsk';
    case ASIA_ORAL = 'Asia/Oral';
    case ASIA_PHNOM_PENH = 'Asia/Phnom_Penh';
    case ASIA_PONTIANAK = 'Asia/Pontianak';
    case ASIA_PYONGYANG = 'Asia/Pyongyang';
    case ASIA_QATAR = 'Asia/Qatar';
    case ASIA_QYZYLORDA = 'Asia/Qyzylorda';
    case ASIA_RIYADH = 'Asia/Riyadh';
    case ASIA_SAIGON = 'Asia/Saigon';
    case ASIA_SAKHALIN = 'Asia/Sakhalin';
    case ASIA_SAMARKAND = 'Asia/Samarkand';
    case ASIA_SEOUL = 'Asia/Seoul';
    case ASIA_SHANGHAI = 'Asia/Shanghai';
    case ASIA_SINGAPORE = 'Asia/Singapore';
    case ASIA_SREDNEKOLYMSK = 'Asia/Srednekolymsk';
    case ASIA_TAIPEI = 'Asia/Taipei';
    case ASIA_TASHKENT = 'Asia/Tashkent';
    case ASIA_TBILISI = 'Asia/Tbilisi';
    case ASIA_TEHRAN = 'Asia/Tehran';
    case ASIA_THIMPHU = 'Asia/Thimphu';
    case ASIA_TOKYO = 'Asia/Tokyo';
    case ASIA_TOMSK = 'Asia/Tomsk';
    case ASIA_ULAANBAATAR = 'Asia/Ulaanbaatar';
    case ASIA_URUMQI = 'Asia/Urumqi';
    case ASIA_UST_NERA = 'Asia/Ust-Nera';
    case ASIA_VIENTIANE = 'Asia/Vientiane';
    case ASIA_VLADIVOSTOK = 'Asia/Vladivostok';
    case ASIA_YAKUTSK = 'Asia/Yakutsk';
    case ASIA_YEKATERINBURG = 'Asia/Yekaterinburg';
    case ASIA_YEREVAN = 'Asia/Yerevan';
    case ATLANTIC_AZORES = 'Atlantic/Azores';
    case ATLANTIC_BERMUDA = 'Atlantic/Bermuda';
    case ATLANTIC_CANARY = 'Atlantic/Canary';
    case ATLANTIC_CAPE_VERDE = 'Atlantic/Cape_Verde';
    case ATLANTIC_FAROE = 'Atlantic/Faroe';
    case ATLANTIC_MADEIRA = 'Atlantic/Madeira';
    case ATLANTIC_SOUTH_GEORGIA = 'Atlantic/South_Georgia';
    case ATLANTIC_STANLEY = 'Atlantic/Stanley';
    case AUSTRALIA_ADELAIDE = 'Australia/Adelaide';
    case AUSTRALIA_BRISBANE = 'Australia/Brisbane';
    case AUSTRALIA_BROKEN_HILL = 'Australia/Broken_Hill';
    case AUSTRALIA_CANBERRA = 'Australia/Canberra';
    case AUSTRALIA_DARWIN = 'Australia/Darwin';
    case AUSTRALIA_EUCLA = 'Australia/Eucla';
    case AUSTRALIA_HOBART = 'Australia/Hobart';
    case AUSTRALIA_LHI = 'Australia/LHI';
    case AUSTRALIA_LINDEMAN = 'Australia/Lindeman';
    case AUSTRALIA_MELBOURNE = 'Australia/Melbourne';
    case AUSTRALIA_PERTH = 'Australia/Perth';
    case AUSTRALIA_SYDNEY = 'Australia/Sydney';
    case EUROPE_AMSTERDAM = 'Europe/Amsterdam';
    case EUROPE_ANDORRA = 'Europe/Andorra';
    case EUROPE_ASTRAKHAN = 'Europe/Astrakhan';
    case EUROPE_ATHENS = 'Europe/Athens';
    case EUROPE_BELGRADE = 'Europe/Belgrade';
    case EUROPE_BERLIN = 'Europe/Berlin';
    case EUROPE_BRATISLAVA = 'Europe/Bratislava';
    case EUROPE_BRUSSELS = 'Europe/Brussels';
    case EUROPE_BUCHAREST = 'Europe/Bucharest';
    case EUROPE_BUDAPEST = 'Europe/Budapest';
    case EUROPE_BUSYGINO = 'Europe/Busygino';
    case EUROPE_CHISINAU = 'Europe/Chisinau';
    case EUROPE_COPENHAGEN = 'Europe/Copenhagen';
    case EUROPE_DUBLIN = 'Europe/Dublin';
    case EUROPE_GIBRALTAR = 'Europe/Gibraltar';
    case EUROPE_GUERNSEY = 'Europe/Guernsey';
    case EUROPE_HELSINKI = 'Europe/Helsinki';
    case EUROPE_ISLE_OF_MAN = 'Europe/Isle_of_Man';
    case EUROPE_ISTANBUL = 'Europe/Istanbul';
    case EUROPE_JERSEY = 'Europe/Jersey';
    case EUROPE_KALININGRAD = 'Europe/Kaliningrad';
    case EUROPE_KIEV = 'Europe/Kiev';
    case EUROPE_KIROV = 'Europe/Kirov';
    case EUROPE_LISBON = 'Europe/Lisbon';
    case EUROPE_LJUBLJANA = 'Europe/Ljubljana';
    case EUROPE_LONDON = 'Europe/London';
    case EUROPE_LUXEMBOURG = 'Europe/Luxembourg';
    case EUROPE_LYON = 'Europe/Lyon';
    case EUROPE_MADRID = 'Europe/Madrid';
    case EUROPE_MALTA = 'Europe/Malta';
    case EUROPE_MARIEHAMN = 'Europe/Mariehamn';
    case EUROPE_MINSK = 'Europe/Minsk';
    case EUROPE_MONACO = 'Europe/Monaco';
    case EUROPE_MOSCOW = 'Europe/Moscow';
    case EUROPE_OSLO = 'Europe/Oslo';
    case EUROPE_PARIS = 'Europe/Paris';
    case EUROPE_PODGORICA = 'Europe/Podgorica';
    case EUROPE_PRAGUE = 'Europe/Prague';
    case EUROPE_RIGA = 'Europe/Riga';
    case EUROPE_ROME = 'Europe/Rome';
    case EUROPE_SAMARA = 'Europe/Samara';
    case EUROPE_SARAJEVO = 'Europe/Sarajevo';
    case EUROPE_SARATOV = 'Europe/Saratov';
    case EUROPE_SIMFEROPOL = 'Europe/Simferopol';
    case EUROPE_SKOPJE = 'Europe/Skopje';
    case EUROPE_SOFIA = 'Europe/Sofia';
    case EUROPE_STOCKHOLM = 'Europe/Stockholm';
    case EUROPE_TALLINN = 'Europe/Tallinn';
    case EUROPE_TIRANE = 'Europe/Tirane';
    case EUROPE_ULYANOVSK = 'Europe/Ulyanovsk';
    case EUROPE_UZHGOROD = 'Europe/Uzhgorod';
    case EUROPE_VADUZ = 'Europe/Vaduz';
    case EUROPE_VATICAN = 'Europe/Vatican';
    case EUROPE_VIENNA = 'Europe/Vienna';
    case EUROPE_VILNIUS = 'Europe/Vilnius';
    case EUROPE_VOLGOGRAD = 'Europe/Volgograd';
    case EUROPE_WARSAW = 'Europe/Warsaw';
    case EUROPE_ZAGREB = 'Europe/Zagreb';
    case EUROPE_ZAPOROZHYE = 'Europe/Zaporozhye';
    case INDIAN_ANTANANARIVO = 'Indian/Antananarivo';
    case INDIAN_CHAGOS = 'Indian/Chagos';
    case INDIAN_CHRISTMAS = 'Indian/Christmas';
    case INDIAN_COMORO = 'Indian/Comoro';
    case INDIAN_KERGUELEN = 'Indian/Kerguelen';
    case INDIAN_MAHE = 'Indian/Mahe';
    case INDIAN_MALDIVES = 'Indian/Maldives';
    case INDIAN_MAURITIUS = 'Indian/Mauritius';
    case INDIAN_MAYOTTE = 'Indian/Mayotte';
    case INDIAN_REUNION = 'Indian/Reunion';
    case PACIFIC_APIA = 'Pacific/Apia';
    case PACIFIC_AUCKLAND = 'Pacific/Auckland';
    case PACIFIC_BOUGAINVILLE = 'Pacific/Bougainville';
    case PACIFIC_CHATHAM = 'Pacific/Chatham';
    case PACIFIC_CHUUK = 'Pacific/Chuuk';
    case PACIFIC_EASTER = 'Pacific/Easter';
    case PACIFIC_EFATE = 'Pacific/Efate';
    case PACIFIC_FIJI = 'Pacific/Fiji';
    case PACIFIC_FUNAFUTI = 'Pacific/Funafuti';
    case PACIFIC_GALAPAGOS = 'Pacific/Galapagos';
    case PACIFIC_GAMBIER = 'Pacific/Gambier';
    case PACIFIC_GUADALCANAL = 'Pacific/Guadalcanal';
    case PACIFIC_GUAM = 'Pacific/Guam';
    case PACIFIC_HONOLULU = 'Pacific/Honolulu';
    case PACIFIC_JOHNSTON = 'Pacific/Johnston';
    case PACIFIC_KIRITIMATI = 'Pacific/Kiritimati';
    case PACIFIC_KOSRAE = 'Pacific/Kosrae';
    case PACIFIC_KWAJALEIN = 'Pacific/Kwajalein';
    case PACIFIC_MAJURO = 'Pacific/Majuro';
    case PACIFIC_MARQUESAS = 'Pacific/Marquesas';
    case PACIFIC_MIDWAY = 'Pacific/Midway';
    case PACIFIC_NAURU = 'Pacific/Nauru';
    case PACIFIC_NIUE = 'Pacific/Niue';
    case PACIFIC_NORFOLK = 'Pacific/Norfolk';
    case PACIFIC_NOUMEA = 'Pacific/Noumea';
    case PACIFIC_PAGO_PAGO = 'Pacific/Pago_Pago';
    case PACIFIC_PALAU = 'Pacific/Palau';
    case PACIFIC_PITCAIRN = 'Pacific/Pitcairn';
    case PACIFIC_POHNPEI = 'Pacific/Pohnpei';
    case PACIFIC_PORT_MORESBY = 'Pacific/Port_Moresby';
    case PACIFIC_RAROTONGA = 'Pacific/Rarotonga';
    case PACIFIC_SAIPAN = 'Pacific/Saipan';
    case PACIFIC_SAMOA = 'Pacific/Samoa';
    case PACIFIC_TAHITI = 'Pacific/Tahiti';
    case PACIFIC_TARAWA = 'Pacific/Tarawa';
    case PACIFIC_TONGATAPU = 'Pacific/Tongatapu';
    case PACIFIC_WAKE = 'Pacific/Wake';
    case PACIFIC_WALLIS = 'Pacific/Wallis';
    case UTC = 'UTC';

    /**
     * タイムゾーンの表示名を取得
     */
    public function label(): string
    {
        return match ($this) {
            self::ASIA_TOKYO => '日本標準時 (JST)',
            self::UTC => '協定世界時 (UTC)',
            self::AMERICA_NEW_YORK => '米国東部時間 (EST/EDT)',
            self::AFRICA_ABIDJAN => 'グリニッジ標準時 (GMT)',
            self::AFRICA_ALGIERS => '中央ヨーロッパ時間 (CET)',
            self::AFRICA_BISSAU => 'グリニッジ標準時 (GMT)',
            self::AFRICA_CAIRO => '東ヨーロッパ時間 (EET)',
            self::AFRICA_CASABLANCA => '西ヨーロッパ時間 (WET)',
            self::AFRICA_CEUTA => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::AFRICA_EL_AAIUN => '西ヨーロッパ時間 (WET)',
            self::AFRICA_JOHANNESBURG => '南アフリカ標準時 (SAST)',
            self::AFRICA_JUBA => '中央アフリカ時間 (CAT)',
            self::AFRICA_KHARTOUM => '中央アフリカ時間 (CAT)',
            self::AFRICA_LAGOS => '西アフリカ時間 (WAT)',
            self::AFRICA_LIBREVILLE => '西アフリカ時間 (WAT)',
            self::AFRICA_MAPUTO => '中央アフリカ時間 (CAT)',
            self::AFRICA_MONROVIA => 'グリニッジ標準時 (GMT)',
            self::AFRICA_NAIROBI => '東アフリカ時間 (EAT)',
            self::AFRICA_NDJAMENA => '西アフリカ時間 (WAT)',
            self::AFRICA_NOUAKCHOTT => 'グリニッジ標準時 (GMT)',
            self::AFRICA_SAO_TOME => 'グリニッジ標準時 (GMT)',
            self::AFRICA_TRIPOLI => '東ヨーロッパ時間 (EET)',
            self::AFRICA_TUNIS => '中央ヨーロッパ時間 (CET)',
            self::AFRICA_WINDHOEK => '中央アフリカ時間 (CAT)',
            self::AMERICA_ADAK => 'ハワイ・アリューシャン標準時 (HST) / ハワイ・アリューシャン夏時間 (HDT)',
            self::AMERICA_ANCHORAGE => 'アラスカ標準時 (AKST) / アラスカ夏時間 (AKDT)',
            self::AMERICA_ANGUILLA => '大西洋標準時 (AST)',
            self::AMERICA_ANTIGUA => '大西洋標準時 (AST)',
            self::AMERICA_ARAGUAINA => 'ブラジリア時間 (BRT)',
            self::AMERICA_ARUBA => '大西洋標準時 (AST)',
            self::AMERICA_ASUNCION => 'パラグアイ標準時 (PYT) / パラグアイ夏時間 (PYST)',
            self::AMERICA_ATIKOKAN => '東部時間 (ET)',
            self::AMERICA_BAHIA => 'ブラジリア時間 (BRT)',
            self::AMERICA_BAHIA_BANDERAS => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AMERICA_BARBADOS => '大西洋標準時 (AST)',
            self::AMERICA_BELEM => 'ブラジリア時間 (BRT)',
            self::AMERICA_BELIZE => '中部標準時 (CST)',
            self::AMERICA_BOA_VISTA => 'アマゾナス時間 (AMT)',
            self::AMERICA_BOGOTA => 'コロンビア時間 (COT)',
            self::AMERICA_BOISE => '山岳部標準時 (MST) / 山岳部夏時間 (MDT)',
            self::AMERICA_CAMBRIDGE_BAY => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AMERICA_CAMPO_GRANDE => 'アマゾナス時間 (AMT)',
            self::AMERICA_CANCUN => '東部標準時 (EST)',
            self::AMERICA_CARACAS => 'ベネズエラ時間 (VET)',
            self::AMERICA_CAYMAN => '東部標準時 (EST)',
            self::AMERICA_CHICAGO => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AMERICA_CHIHUAHUA => '山岳部標準時 (MST)',
            self::AMERICA_COMODORO_RIVADAVIA => 'アルゼンチン標準時 (ART)',
            self::AMERICA_COSTA_RICA => '中部標準時 (CST)',
            self::AMERICA_CRESTON => '山岳部標準時 (MST)',
            self::AMERICA_CUIABA => 'アマゾナス時間 (AMT)',
            self::AMERICA_CURACAO => '大西洋標準時 (AST)',
            self::AMERICA_DANVILLE => '東部時間 (ET)',
            self::AMERICA_DETROIT => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AMERICA_DOMINICA => '大西洋標準時 (AST)',
            self::AMERICA_EDMONTON => '山岳部標準時 (MST) / 山岳部夏時間 (MDT)',
            self::AMERICA_EIRUNEPE => 'アマゾナス時間 (AMT)',
            self::AMERICA_EL_SALVADOR => '中部標準時 (CST)',
            self::AMERICA_FORTALEZA => 'ブラジリア時間 (BRT)',
            self::AMERICA_GLACE_BAY => '大西洋標準時 (AST) / 大西洋夏時間 (ADT)',
            self::AMERICA_GOOSE_BAY => '大西洋標準時 (AST) / 大西洋夏時間 (ADT)',
            self::AMERICA_GRAND_TURK => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AMERICA_GRENADA => '大西洋標準時 (AST)',
            self::AMERICA_GUATEMALA => '中部標準時 (CST)',
            self::AMERICA_GUAYAQUIL => 'エクアドル時間 (ECT)',
            self::AMERICA_GUYANA => 'ガイアナ時間 (GYT)',
            self::AMERICA_HALIFAX => '大西洋標準時 (AST) / 大西洋夏時間 (ADT)',
            self::AMERICA_HAVANA => 'キューバ標準時 (CST) / キューバ夏時間 (CDT)',
            self::AMERICA_HERMOSILLO => '山岳部標準時 (MST)',
            self::AMERICA_INDIANAPOLIS => '東部時間 (ET)',
            self::AMERICA_INUVIK => '山岳部標準時 (MST) / 山岳部夏時間 (MDT)',
            self::AMERICA_IQUITOS => 'ペルー時間 (PET)',
            self::AMERICA_JAMAICA => '東部標準時 (EST)',
            self::AMERICA_JUNEAU => 'アラスカ標準時 (AKST) / アラスカ夏時間 (AKDT)',
            self::AMERICA_KENTUCKY_LOUISVILLE => '東部時間 (ET)',
            self::AMERICA_KRALENDIJK => '大西洋標準時 (AST)',
            self::AMERICA_LA_PAZ => 'ボリビア時間 (BOT)',
            self::AMERICA_LIMA => 'ペルー時間 (PET)',
            self::AMERICA_LOS_ANGELES => '太平洋標準時 (PST) / 太平洋夏時間 (PDT)',
            self::AMERICA_LOWER_PRINCE => '大西洋標準時 (AST)',
            self::AMERICA_MACEIO => 'ブラジリア時間 (BRT)',
            self::AMERICA_MANAGUA => '中部標準時 (CST)',
            self::AMERICA_MANAUS => 'アマゾナス時間 (AMT)',
            self::AMERICA_MARIGOT => '大西洋標準時 (AST)',
            self::AMERICA_MARTINIQUE => '大西洋標準時 (AST)',
            self::AMERICA_MATAMOROS => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AMERICA_MAZATLAN => '山岳部標準時 (MST) / 山岳部夏時間 (MDT)',
            self::AMERICA_MENOMINEE => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AMERICA_MERIDA => '中部標準時 (CST)',
            self::AMERICA_METROPOLIS => '東部時間 (ET)',
            self::AMERICA_MEXICO_CITY => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AMERICA_MIQUELON => 'サンピエール・ミクロン標準時 (PMST) / サンピエール・ミクロン夏時間 (PMDT)',
            self::AMERICA_MONCTON => '大西洋標準時 (AST) / 大西洋夏時間 (ADT)',
            self::AMERICA_MONTEVIDEO => 'ウルグアイ標準時 (UYT)',
            self::AMERICA_MONTERREY => '中部標準時 (CST)',
            self::AMERICA_MONTREAL => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AMERICA_NASSAU => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AMERICA_NIPIGON => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AMERICA_NOME => 'アラスカ標準時 (AKST) / アラスカ夏時間 (AKDT)',
            self::AMERICA_NORONHA => 'フェルナンド・デ・ノローニャ時間 (FNT)',
            self::AMERICA_NORTH_DAKOTA_CENTER => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AMERICA_NORTH_DAKOTA_NEW_SALEM => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AMERICA_NUUK => '西グリーンランド時間 (WGT) / 西グリーンランド夏時間 (WSD)',
            self::AMERICA_OJINAGA => '山岳部標準時 (MST) / 山岳部夏時間 (MDT)',
            self::AMERICA_PANAMA => '東部標準時 (EST)',
            self::AMERICA_PANGNIRTUNG => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AMERICA_PARAMARIBO => 'スリナム時間 (SRT)',
            self::AMERICA_PHOENIX => '山岳部標準時 (MST)',
            self::AMERICA_PORT_AU_PRINCE => '東部標準時 (EST)',
            self::AMERICA_PORT_OF_SPAIN => '大西洋標準時 (AST)',
            self::AMERICA_PORTO_VELHO => 'アマゾナス時間 (AMT)',
            self::AMERICA_PUERTO_RICO => '大西洋標準時 (AST)',
            self::AMERICA_PUNT_ARENAS => 'チリ時間 (CLT)',
            self::AMERICA_RAINY_RIVER => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AMERICA_RECIFE => 'ブラジリア時間 (BRT)',
            self::AMERICA_REGINA => '中部標準時 (CST)',
            self::AMERICA_RIO_BRANCO => 'アマゾナス時間 (AMT)',
            self::AMERICA_SANTIAGO => 'チリ時間 (CLT) / チリ夏時間 (CLST)',
            self::AMERICA_SANTO_DOMINGO => '大西洋標準時 (AST)',
            self::AMERICA_SAO_PAULO => 'ブラジリア時間 (BRT)',
            self::AMERICA_SCORESBYSUND => '東グリーンランド時間 (EGT) / 東グリーンランド夏時間 (ESD)',
            self::AMERICA_SHIPROCK => '山岳部標準時 (MST) / 山岳部夏時間 (MDT)',
            self::AMERICA_SITKA => 'アラスカ標準時 (AKST) / アラスカ夏時間 (AKDT)',
            self::AMERICA_ST_BARTHELEMY => '大西洋標準時 (AST)',
            self::AMERICA_ST_JOHNS => 'ニューファンドランド標準時 (NST) / ニューファンドランド夏時間 (NDT)',
            self::AMERICA_ST_KITTS => '大西洋標準時 (AST)',
            self::AMERICA_ST_LUCIA => '大西洋標準時 (AST)',
            self::AMERICA_ST_THOMAS => '大西洋標準時 (AST)',
            self::AMERICA_ST_VINCENT => '大西洋標準時 (AST)',
            self::AMERICA_SUDBURY => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AMERICA_SWIFT_CURRENT => '中部標準時 (CST)',
            self::AMERICA_TEGUCIGALPA => '中部標準時 (CST)',
            self::AMERICA_THULE => '大西洋標準時 (AST) / 大西洋夏時間 (ADT)',
            self::AMERICA_THUNDER_BAY => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AMERICA_TIJUANA => '太平洋標準時 (PST) / 太平洋夏時間 (PDT)',
            self::AMERICA_TORONTO => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AMERICA_TORTOLA => '大西洋標準時 (AST)',
            self::AMERICA_VANCOUVER => '太平洋標準時 (PST) / 太平洋夏時間 (PDT)',
            self::AMERICA_WHITEHORSE => '太平洋標準時 (PST) / 太平洋夏時間 (PDT)',
            self::AMERICA_WINNIPEG => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AMERICA_YAKUTAT => 'アラスカ標準時 (AKST) / アラスカ夏時間 (AKDT)',
            self::AMERICA_YELLOWKNIFE => '山岳部標準時 (MST) / 山岳部夏時間 (MDT)',
            self::ANTARCTICA_CASEY => '協定世界時+11:00 (UTC+11)',
            self::ANTARCTICA_DAVIS => '協定世界時+7:00 (UTC+7)',
            self::ANTARCTICA_DUMONT_D_URVILLE => '協定世界時+10:00 (UTC+10)',
            self::ANTARCTICA_MACQUARIE => 'オーストラリア東部夏時間 (AEDT)',
            self::ANTARCTICA_MAWSON => '協定世界時+5:00 (UTC+5)',
            self::ANTARCTICA_PALMER => 'チリ夏時間 (CLST)',
            self::ANTARCTICA_ROTHERA => 'チリ時間 (CLT)',
            self::ANTARCTICA_SYOWA => '協定世界時+3:00 (UTC+3)',
            self::ANTARCTICA_TROLL => 'グリニッジ標準時 (GMT) / 中央ヨーロッパ時間 (CET)',
            self::ANTARCTICA_VOSTOK => '協定世界時+6:00 (UTC+6)',
            self::ARCTIC_LONGYEARBYEN => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::ASIA_ADEN => 'アラビア標準時 (AST)',
            self::ASIA_ALMATY => 'カザフスタン東部時間 (ALMT)',
            self::ASIA_AMMAN => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::ASIA_ANADYR => 'マガダン時間 (MAGT)',
            self::ASIA_AQTAU => 'カザフスタン西部時間 (AQTT)',
            self::ASIA_AQTUBE => 'カザフスタン西部時間 (AQTT)',
            self::ASIA_ASHGABAT => 'トルクメニスタン時間 (TMT)',
            self::ASIA_ATYRAU => 'カザフスタン西部時間 (AQTT)',
            self::ASIA_BAGHDAD => 'アラビア標準時 (AST)',
            self::ASIA_BAKU => 'アゼルバイジャン時間 (AZT) / アゼルバイジャン夏時間 (AZST)',
            self::ASIA_BANGKOK => 'インドシナ時間 (ICT)',
            self::ASIA_BARNAUL => 'ロシア標準時 (KRAT)',
            self::ASIA_BEIRUT => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::ASIA_BISHKEK => 'キルギスタン時間 (KGT)',
            self::ASIA_BRUNEI => 'ブルネイ・ダルサラーム時間 (BNT)',
            self::ASIA_CHITA => 'ヤクーツク時間 (YAKT)',
            self::ASIA_CHOIBALSAN => 'チョイバルサン時間 (CHOT)',
            self::ASIA_COLOMBO => 'スリランカ標準時 (SLT)',
            self::ASIA_DAMASCUS => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::ASIA_DHAKA => 'バングラデシュ標準時 (BDT)',
            self::ASIA_DILI => '東ティモール時間 (TLT)',
            self::ASIA_DUBAI => '湾岸標準時 (GST)',
            self::ASIA_DUSHANBE => 'タジキスタン時間 (TJT)',
            self::ASIA_FAMAGUSTA => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::ASIA_GANDHINAGAR => 'インド標準時 (IST)',
            self::ASIA_GAZA => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::ASIA_HEBRON => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::ASIA_HONG_KONG => '香港時間 (HKT)',
            self::ASIA_HOVD => 'ホブド時間 (HOVT)',
            self::ASIA_IRKUTSK => 'イルクーツク時間 (IRKT)',
            self::ASIA_ISTANBUL => 'トルコ時間 (TRT)',
            self::ASIA_JAKARTA => '西部インドネシア時間 (WIB)',
            self::ASIA_JAYAPURA => '東部インドネシア時間 (WIT)',
            self::ASIA_JERUSALEM => 'イスラエル標準時 (IST) / イスラエル夏時間 (IDT)',
            self::ASIA_KABUL => 'アフガニスタン時間 (AFT)',
            self::ASIA_KAMCHATKA => 'カムチャツカ時間 (PETT)',
            self::ASIA_KARACHI => 'パキスタン標準時 (PKT)',
            self::ASIA_KASHGAR => '中国標準時 (CST)',
            self::ASIA_KATHMANDU => 'ネパール時間 (NPT)',
            self::ASIA_KHANDYGA => 'ヤクーツク時間 (YAKT)',
            self::ASIA_KOLKATA => 'インド標準時 (IST)',
            self::ASIA_KRASNOYARSK => 'クラスノヤルスク時間 (KRAT)',
            self::ASIA_KUALA_LUMPUR => 'マレーシア標準時 (MYT)',
            self::ASIA_KUCHING => 'マレーシア時間 (MYT)',
            self::ASIA_KUWAIT => 'アラビア標準時 (AST)',
            self::ASIA_MACAU => 'マカオ標準時 (MST) / マカオ夏時間 (MMT)',
            self::ASIA_MAGADAN => 'マガダン時間 (MAGT)',
            self::ASIA_MAKASSAR => '中部インドネシア時間 (WITA)',
            self::ASIA_MANILA => 'フィリピン標準時 (PHT)',
            self::ASIA_MUSCAT => '湾岸標準時 (GST)',
            self::ASIA_NICOSIA => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::ASIA_NOVOKUZNETSK => 'クラスノヤルスク時間 (KRAT)',
            self::ASIA_NOVOSIBIRSK => 'ノボシビルスク時間 (NOVT)',
            self::ASIA_OMSK => 'オムスク時間 (OMST)',
            self::ASIA_ORAL => 'カザフスタン西部時間 (AQTT)',
            self::ASIA_PHNOM_PENH => 'インドシナ時間 (ICT)',
            self::ASIA_PONTIANAK => '西部インドネシア時間 (WIB)',
            self::ASIA_PYONGYANG => '平壌時間 (PYT)',
            self::ASIA_QATAR => 'アラビア標準時 (AST)',
            self::ASIA_QYZYLORDA => 'カザフスタン西部時間 (AQTT)',
            self::ASIA_RIYADH => 'アラビア標準時 (AST)',
            self::ASIA_SAIGON => 'インドシナ時間 (ICT)',
            self::ASIA_SAKHALIN => 'サハリン時間 (SAKT)',
            self::ASIA_SAMARKAND => 'ウズベキスタン時間 (UZT)',
            self::ASIA_SEOUL => '韓国標準時 (KST)',
            self::ASIA_SHANGHAI => '中国標準時 (CST)',
            self::ASIA_SINGAPORE => 'シンガポール標準時 (SGT)',
            self::ASIA_SREDNEKOLYMSK => 'マガダン時間 (MAGT)',
            self::ASIA_TAIPEI => '台北標準時 (CST)',
            self::ASIA_TASHKENT => 'ウズベキスタン時間 (UZT)',
            self::ASIA_TBILISI => 'グルジア時間 (GET)',
            self::ASIA_TEHRAN => 'イラン標準時 (IRST) / イラン夏時間 (IRDT)',
            self::ASIA_THIMPHU => 'ブータン時間 (BTT)',
            self::ASIA_TOMSK => 'トムスク時間 (TOMT)',
            self::ASIA_ULAANBAATAR => 'ウランバートル時間 (ULAT)',
            self::ASIA_URUMQI => '中国標準時 (CST)',
            self::ASIA_UST_NERA => 'ウラジオストク時間 (VLAT)',
            self::ASIA_VIENTIANE => 'インドシナ時間 (ICT)',
            self::ASIA_VLADIVOSTOK => 'ウラジオストク時間 (VLAT)',
            self::ASIA_YAKUTSK => 'ヤクーツク時間 (YAKT)',
            self::ASIA_YEKATERINBURG => 'エカテリンブルク時間 (YEKT)',
            self::ASIA_YEREVAN => 'アルメニア時間 (AMT)',
            self::ATLANTIC_AZORES => 'アゾレス標準時 (AZOT) / アゾレス夏時間 (AZOST)',
            self::ATLANTIC_BERMUDA => '大西洋標準時 (AST) / 大西洋夏時間 (ADT)',
            self::ATLANTIC_CANARY => '西ヨーロッパ時間 (WET) / 西ヨーロッパ夏時間 (WEST)',
            self::ATLANTIC_CAPE_VERDE => 'カーボベルデ時間 (CVT)',
            self::ATLANTIC_FAROE => '西ヨーロッパ時間 (WET) / 西ヨーロッパ夏時間 (WEST)',
            self::ATLANTIC_MADEIRA => '西ヨーロッパ時間 (WET) / 西ヨーロッパ夏時間 (WEST)',
            self::ATLANTIC_SOUTH_GEORGIA => '南ジョージア時間 (GST)',
            self::ATLANTIC_STANLEY => 'フォークランド諸島標準時 (FKT)',
            self::AUSTRALIA_ADELAIDE => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AUSTRALIA_BRISBANE => '東部標準時 (EST)',
            self::AUSTRALIA_BROKEN_HILL => '中部標準時 (CST) / 中部夏時間 (CDT)',
            self::AUSTRALIA_CANBERRA => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AUSTRALIA_DARWIN => '中部標準時 (CST)',
            self::AUSTRALIA_EUCLA => '中部西部標準時 (CWST)',
            self::AUSTRALIA_HOBART => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AUSTRALIA_LHI => 'ロード・ハウ標準時 (LHST) / ロード・ハウ夏時間 (LHDT)',
            self::AUSTRALIA_LINDEMAN => '東部標準時 (EST)',
            self::AUSTRALIA_MELBOURNE => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::AUSTRALIA_PERTH => '西部標準時 (WST)',
            self::AUSTRALIA_SYDNEY => '東部標準時 (EST) / 東部夏時間 (EDT)',
            self::EUROPE_AMSTERDAM => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_ANDORRA => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_ASTRAKHAN => 'モスクワ時間 (MSK)',
            self::EUROPE_ATHENS => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::EUROPE_BELGRADE => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_BERLIN => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_BRATISLAVA => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_BRUSSELS => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_BUCHAREST => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::EUROPE_BUDAPEST => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_BUSYGINO => 'モスクワ時間 (MSK)',
            self::EUROPE_CHISINAU => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::EUROPE_COPENHAGEN => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_DUBLIN => 'グリニッジ標準時 (GMT) / アイルランド標準時 (IST)',
            self::EUROPE_GIBRALTAR => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_GUERNSEY => 'グリニッジ標準時 (GMT) / 英国夏時間 (BST)',
            self::EUROPE_HELSINKI => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::EUROPE_ISLE_OF_MAN => 'グリニッジ標準時 (GMT) / 英国夏時間 (BST)',
            self::EUROPE_ISTANBUL => 'トルコ時間 (TRT)',
            self::EUROPE_JERSEY => 'グリニッジ標準時 (GMT) / 英国夏時間 (BST)',
            self::EUROPE_KALININGRAD => '東ヨーロッパ時間 (EET)',
            self::EUROPE_KIEV => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::EUROPE_KIROV => 'モスクワ時間 (MSK)',
            self::EUROPE_LISBON => '西ヨーロッパ時間 (WET) / 西ヨーロッパ夏時間 (WEST)',
            self::EUROPE_LJUBLJANA => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_LONDON => 'グリニッジ標準時 (GMT) / 英国夏時間 (BST)',
            self::EUROPE_LUXEMBOURG => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_LYON => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_MADRID => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_MALTA => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_MARIEHAMN => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::EUROPE_MINSK => '東ヨーロッパ時間 (EET)',
            self::EUROPE_MONACO => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_MOSCOW => 'モスクワ時間 (MSK)',
            self::EUROPE_OSLO => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_PARIS => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_PODGORICA => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_PRAGUE => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_RIGA => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::EUROPE_ROME => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_SAMARA => 'サマラ時間 (SAMT)',
            self::EUROPE_SARAJEVO => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_SARATOV => 'サラトフ時間 (SART)',
            self::EUROPE_SIMFEROPOL => 'モスクワ時間 (MSK)',
            self::EUROPE_SKOPJE => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_SOFIA => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::EUROPE_STOCKHOLM => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_TALLINN => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::EUROPE_TIRANE => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_ULYANOVSK => 'ウリヤノフスク時間 (ULYT)',
            self::EUROPE_UZHGOROD => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::EUROPE_VADUZ => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_VATICAN => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_VIENNA => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_VILNIUS => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::EUROPE_VOLGOGRAD => 'ボルゴグラード時間 (VOLT)',
            self::EUROPE_WARSAW => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_ZAGREB => '中央ヨーロッパ時間 (CET) / 中央ヨーロッパ夏時間 (CEST)',
            self::EUROPE_ZAPOROZHYE => '東ヨーロッパ時間 (EET) / 東ヨーロッパ夏時間 (EEST)',
            self::INDIAN_ANTANANARIVO => '東アフリカ時間 (EAT)',
            self::INDIAN_CHAGOS => '協定世界時+6:00 (UTC+6)',
            self::INDIAN_CHRISTMAS => '協定世界時+7:00 (UTC+7)',
            self::INDIAN_COMORO => '東アフリカ時間 (EAT)',
            self::INDIAN_KERGUELEN => '協定世界時+5:00 (UTC+5)',
            self::INDIAN_MAHE => '協定世界時+4:00 (UTC+4)',
            self::INDIAN_MALDIVES => 'モルディブ時間 (MVT)',
            self::INDIAN_MAURITIUS => 'モーリシャス時間 (MUT)',
            self::INDIAN_MAYOTTE => '東アフリカ時間 (EAT)',
            self::INDIAN_REUNION => '協定世界時+4:00 (UTC+4)',
            self::PACIFIC_APIA => 'サモア標準時 (WST)',
            self::PACIFIC_AUCKLAND => 'ニュージーランド標準時 (NZST) / ニュージーランド夏時間 (NZDT)',
            self::PACIFIC_BOUGAINVILLE => 'ソロモン諸島時間 (SBT)',
            self::PACIFIC_CHATHAM => 'チャタム標準時 (CHAST) / チャタム夏時間 (CHADT)',
            self::PACIFIC_CHUUK => '協定世界時+10:00 (UTC+10)',
            self::PACIFIC_EASTER => 'イースター島標準時 (EAST) / イースター島夏時間 (EASST)',
            self::PACIFIC_EFATE => 'バヌアツ時間 (VUT)',
            self::PACIFIC_FIJI => 'フィジー時間 (FJT)',
            self::PACIFIC_FUNAFUTI => 'ツバル時間 (TVT)',
            self::PACIFIC_GALAPAGOS => 'ガラパゴス時間 (GALT)',
            self::PACIFIC_GAMBIER => '協定世界時-9:00 (UTC-9)',
            self::PACIFIC_GUADALCANAL => 'ソロモン諸島時間 (SBT)',
            self::PACIFIC_GUAM => 'チャモロ標準時 (CHST)',
            self::PACIFIC_HONOLULU => 'ハワイ・アリューシャン標準時 (HST)',
            self::PACIFIC_JOHNSTON => 'ハワイ・アリューシャン標準時 (HST)',
            self::PACIFIC_KIRITIMATI => 'ライン諸島時間 (LINT)',
            self::PACIFIC_KOSRAE => '協定世界時+11:00 (UTC+11)',
            self::PACIFIC_KWAJALEIN => 'マーシャル諸島時間 (MHT)',
            self::PACIFIC_MAJURO => 'マーシャル諸島時間 (MHT)',
            self::PACIFIC_MARQUESAS => 'マルケサス時間 (MART)',
            self::PACIFIC_MIDWAY => 'サモア時間 (SST)',
            self::PACIFIC_NAURU => 'ナウル時間 (NRT)',
            self::PACIFIC_NIUE => 'ニウエ時間 (NUT)',
            self::PACIFIC_NORFOLK => 'ノーフォーク島時間 (NFT)',
            self::PACIFIC_NOUMEA => 'ニューカレドニア時間 (NCT)',
            self::PACIFIC_PAGO_PAGO => 'サモア時間 (SST)',
            self::PACIFIC_PALAU => 'パラオ時間 (PWT)',
            self::PACIFIC_PITCAIRN => 'ピトケアン諸島時間 (PST)',
            self::PACIFIC_POHNPEI => '協定世界時+11:00 (UTC+11)',
            self::PACIFIC_PORT_MORESBY => 'パプアニューギニア時間 (PGT)',
            self::PACIFIC_RAROTONGA => 'クック諸島時間 (CKT)',
            self::PACIFIC_SAIPAN => 'チャモロ標準時 (CHST)',
            self::PACIFIC_SAMOA => 'サモア標準時 (WST)',
            self::PACIFIC_TAHITI => 'タヒチ時間 (TAHT)',
            self::PACIFIC_TARAWA => 'キリバス時間 (KIBT)',
            self::PACIFIC_TONGATAPU => 'トンガ時間 (TOT)',
            self::PACIFIC_WAKE => 'ウェーク島時間 (WAKT)',
            self::PACIFIC_WALLIS => 'ウォリス・フツナ時間 (WFT)',
        };
    }

    public function timeDiff(): string
    {
        return match ($this) {
            self::ASIA_TOKYO => '+09:00',
            self::UTC => '+00:00',
            self::AMERICA_NEW_YORK => '-04:00', // 現在（2025年6月）は夏時間のため EDT
            self::AFRICA_ABIDJAN => '+00:00',
            self::AFRICA_ALGIERS => '+01:00',
            self::AFRICA_BISSAU => '+00:00',
            self::AFRICA_CAIRO => '+03:00', // 夏時間
            self::AFRICA_CASABLANCA => '+01:00',
            self::AFRICA_CEUTA => '+02:00', // 夏時間
            self::AFRICA_EL_AAIUN => '+01:00',
            self::AFRICA_JOHANNESBURG => '+02:00',
            self::AFRICA_JUBA => '+02:00',
            self::AFRICA_KHARTOUM => '+02:00',
            self::AFRICA_LAGOS => '+01:00',
            self::AFRICA_LIBREVILLE => '+01:00',
            self::AFRICA_MAPUTO => '+02:00',
            self::AFRICA_MONROVIA => '+00:00',
            self::AFRICA_NAIROBI => '+03:00',
            self::AFRICA_NDJAMENA => '+01:00',
            self::AFRICA_NOUAKCHOTT => '+00:00',
            self::AFRICA_SAO_TOME => '+00:00',
            self::AFRICA_TRIPOLI => '+02:00',
            self::AFRICA_TUNIS => '+01:00',
            self::AFRICA_WINDHOEK => '+02:00',
            self::AMERICA_ADAK => '-09:00', // 夏時間
            self::AMERICA_ANCHORAGE => '-08:00', // 夏時間
            self::AMERICA_ANGUILLA => '-04:00',
            self::AMERICA_ANTIGUA => '-04:00',
            self::AMERICA_ARAGUAINA => '-03:00',
            self::AMERICA_ARUBA => '-04:00',
            self::AMERICA_ASUNCION => '-04:00', // 夏時間
            self::AMERICA_ATIKOKAN => '-05:00',
            self::AMERICA_BAHIA => '-03:00',
            self::AMERICA_BAHIA_BANDERAS => '-05:00', // 夏時間
            self::AMERICA_BARBADOS => '-04:00',
            self::AMERICA_BELEM => '-03:00',
            self::AMERICA_BELIZE => '-06:00',
            self::AMERICA_BOA_VISTA => '-04:00',
            self::AMERICA_BOGOTA => '-05:00',
            self::AMERICA_BOISE => '-06:00', // 夏時間
            self::AMERICA_CAMBRIDGE_BAY => '-05:00', // 夏時間
            self::AMERICA_CAMPO_GRANDE => '-04:00',
            self::AMERICA_CANCUN => '-05:00',
            self::AMERICA_CARACAS => '-04:00',
            self::AMERICA_CAYMAN => '-05:00',
            self::AMERICA_CHICAGO => '-05:00', // 夏時間
            self::AMERICA_CHIHUAHUA => '-06:00',
            self::AMERICA_COMODORO_RIVADAVIA => '-03:00',
            self::AMERICA_COSTA_RICA => '-06:00',
            self::AMERICA_CRESTON => '-07:00',
            self::AMERICA_CUIABA => '-04:00',
            self::AMERICA_CURACAO => '-04:00',
            self::AMERICA_DANVILLE => '-04:00', // 夏時間
            self::AMERICA_DETROIT => '-04:00', // 夏時間
            self::AMERICA_DOMINICA => '-04:00',
            self::AMERICA_EDMONTON => '-06:00', // 夏時間
            self::AMERICA_EIRUNEPE => '-05:00',
            self::AMERICA_EL_SALVADOR => '-06:00',
            self::AMERICA_FORTALEZA => '-03:00',
            self::AMERICA_GLACE_BAY => '-03:00', // 夏時間
            self::AMERICA_GOOSE_BAY => '-03:00', // 夏時間
            self::AMERICA_GRAND_TURK => '-04:00', // 夏時間
            self::AMERICA_GRENADA => '-04:00',
            self::AMERICA_GUATEMALA => '-06:00',
            self::AMERICA_GUAYAQUIL => '-05:00',
            self::AMERICA_GUYANA => '-04:00',
            self::AMERICA_HALIFAX => '-03:00', // 夏時間
            self::AMERICA_HAVANA => '-04:00', // 夏時間
            self::AMERICA_HERMOSILLO => '-07:00',
            self::AMERICA_INDIANAPOLIS => '-04:00', // 夏時間
            self::AMERICA_INUVIK => '-06:00', // 夏時間
            self::AMERICA_IQUITOS => '-05:00',
            self::AMERICA_JAMAICA => '-05:00',
            self::AMERICA_JUNEAU => '-08:00', // 夏時間
            self::AMERICA_KENTUCKY_LOUISVILLE => '-04:00', // 夏時間
            self::AMERICA_KRALENDIJK => '-04:00',
            self::AMERICA_LA_PAZ => '-04:00',
            self::AMERICA_LIMA => '-05:00',
            self::AMERICA_LOS_ANGELES => '-07:00', // 夏時間
            self::AMERICA_LOWER_PRINCE => '-04:00',
            self::AMERICA_MACEIO => '-03:00',
            self::AMERICA_MANAGUA => '-06:00',
            self::AMERICA_MANAUS => '-04:00',
            self::AMERICA_MARIGOT => '-04:00',
            self::AMERICA_MARTINIQUE => '-04:00',
            self::AMERICA_MATAMOROS => '-05:00', // 夏時間
            self::AMERICA_MAZATLAN => '-06:00', // 夏時間
            self::AMERICA_MENOMINEE => '-05:00', // 夏時間
            self::AMERICA_MERIDA => '-06:00',
            self::AMERICA_METROPOLIS => '-04:00', // 夏時間
            self::AMERICA_MEXICO_CITY => '-05:00', // 夏時間
            self::AMERICA_MIQUELON => '-02:00', // 夏時間
            self::AMERICA_MONCTON => '-03:00', // 夏時間
            self::AMERICA_MONTEVIDEO => '-03:00',
            self::AMERICA_MONTERREY => '-06:00',
            self::AMERICA_MONTREAL => '-04:00', // 夏時間
            self::AMERICA_NASSAU => '-04:00', // 夏時間
            self::AMERICA_NIPIGON => '-04:00', // 夏時間
            self::AMERICA_NOME => '-08:00', // 夏時間
            self::AMERICA_NORONHA => '-02:00',
            self::AMERICA_NORTH_DAKOTA_CENTER => '-05:00', // 夏時間
            self::AMERICA_NORTH_DAKOTA_NEW_SALEM => '-05:00', // 夏時間
            self::AMERICA_NUUK => '-02:00', // 夏時間
            self::AMERICA_OJINAGA => '-06:00', // 夏時間
            self::AMERICA_PANAMA => '-05:00',
            self::AMERICA_PANGNIRTUNG => '-04:00', // 夏時間
            self::AMERICA_PARAMARIBO => '-03:00',
            self::AMERICA_PHOENIX => '-07:00',
            self::AMERICA_PORT_AU_PRINCE => '-04:00', // 夏時間
            self::AMERICA_PORT_OF_SPAIN => '-04:00',
            self::AMERICA_PORTO_VELHO => '-04:00',
            self::AMERICA_PUERTO_RICO => '-04:00',
            self::AMERICA_PUNT_ARENAS => '-03:00',
            self::AMERICA_RAINY_RIVER => '-05:00', // 夏時間
            self::AMERICA_RECIFE => '-03:00',
            self::AMERICA_REGINA => '-06:00',
            self::AMERICA_RIO_BRANCO => '-04:00',
            self::AMERICA_SANTIAGO => '-04:00', // 夏時間
            self::AMERICA_SANTO_DOMINGO => '-04:00',
            self::AMERICA_SAO_PAULO => '-03:00',
            self::AMERICA_SCORESBYSUND => '+00:00', // 夏時間
            self::AMERICA_SHIPROCK => '-06:00', // 夏時間
            self::AMERICA_SITKA => '-08:00', // 夏時間
            self::AMERICA_ST_BARTHELEMY => '-04:00',
            self::AMERICA_ST_JOHNS => '-02:30', // 夏時間
            self::AMERICA_ST_KITTS => '-04:00',
            self::AMERICA_ST_LUCIA => '-04:00',
            self::AMERICA_ST_THOMAS => '-04:00',
            self::AMERICA_ST_VINCENT => '-04:00',
            self::AMERICA_SUDBURY => '-04:00', // 夏時間
            self::AMERICA_SWIFT_CURRENT => '-06:00',
            self::AMERICA_TEGUCIGALPA => '-06:00',
            self::AMERICA_THULE => '-03:00', // 夏時間
            self::AMERICA_THUNDER_BAY => '-04:00', // 夏時間
            self::AMERICA_TIJUANA => '-07:00', // 夏時間
            self::AMERICA_TORONTO => '-04:00', // 夏時間
            self::AMERICA_TORTOLA => '-04:00',
            self::AMERICA_VANCOUVER => '-07:00', // 夏時間
            self::AMERICA_WHITEHORSE => '-07:00', // 夏時間
            self::AMERICA_WINNIPEG => '-05:00', // 夏時間
            self::AMERICA_YAKUTAT => '-08:00', // 夏時間
            self::AMERICA_YELLOWKNIFE => '-06:00', // 夏時間
            self::ANTARCTICA_CASEY => '+11:00',
            self::ANTARCTICA_DAVIS => '+07:00',
            self::ANTARCTICA_DUMONT_D_URVILLE => '+10:00',
            self::ANTARCTICA_MACQUARIE => '+10:00',
            self::ANTARCTICA_MAWSON => '+05:00',
            self::ANTARCTICA_PALMER => '-04:00',
            self::ANTARCTICA_ROTHERA => '-03:00',
            self::ANTARCTICA_SYOWA => '+03:00',
            self::ANTARCTICA_TROLL => '+02:00', // 夏時間
            self::ANTARCTICA_VOSTOK => '+06:00',
            self::ARCTIC_LONGYEARBYEN => '+02:00', // 夏時間
            self::ASIA_ADEN => '+03:00',
            self::ASIA_ALMATY => '+06:00',
            self::ASIA_AMMAN => '+03:00', // 夏時間
            self::ASIA_ANADYR => '+12:00',
            self::ASIA_AQTAU => '+05:00',
            self::ASIA_AQTUBE => '+05:00',
            self::ASIA_ASHGABAT => '+05:00',
            self::ASIA_ATYRAU => '+05:00',
            self::ASIA_BAGHDAD => '+03:00',
            self::ASIA_BAKU => '+04:00', // 夏時間
            self::ASIA_BANGKOK => '+07:00',
            self::ASIA_BARNAUL => '+07:00',
            self::ASIA_BEIRUT => '+03:00', // 夏時間
            self::ASIA_BISHKEK => '+06:00',
            self::ASIA_BRUNEI => '+08:00',
            self::ASIA_CHITA => '+09:00',
            self::ASIA_CHOIBALSAN => '+08:00',
            self::ASIA_COLOMBO => '+05:30',
            self::ASIA_DAMASCUS => '+03:00', // 夏時間
            self::ASIA_DHAKA => '+06:00',
            self::ASIA_DILI => '+09:00',
            self::ASIA_DUBAI => '+04:00',
            self::ASIA_DUSHANBE => '+05:00',
            self::ASIA_FAMAGUSTA => '+03:00', // 夏時間
            self::ASIA_GANDHINAGAR => '+05:30',
            self::ASIA_GAZA => '+03:00', // 夏時間
            self::ASIA_HEBRON => '+03:00', // 夏時間
            self::ASIA_HONG_KONG => '+08:00',
            self::ASIA_HOVD => '+07:00',
            self::ASIA_IRKUTSK => '+08:00',
            self::ASIA_ISTANBUL => '+03:00',
            self::ASIA_JAKARTA => '+07:00',
            self::ASIA_JAYAPURA => '+09:00',
            self::ASIA_JERUSALEM => '+03:00', // 夏時間
            self::ASIA_KABUL => '+04:30',
            self::ASIA_KAMCHATKA => '+12:00',
            self::ASIA_KARACHI => '+05:00',
            self::ASIA_KASHGAR => '+06:00',
            self::ASIA_KATHMANDU => '+05:45',
            self::ASIA_KHANDYGA => '+09:00',
            self::ASIA_KOLKATA => '+05:30',
            self::ASIA_KRASNOYARSK => '+07:00',
            self::ASIA_KUALA_LUMPUR => '+08:00',
            self::ASIA_KUCHING => '+08:00',
            self::ASIA_KUWAIT => '+03:00',
            self::ASIA_MACAU => '+08:00',
            self::ASIA_MAGADAN => '+11:00',
            self::ASIA_MAKASSAR => '+08:00',
            self::ASIA_MANILA => '+08:00',
            self::ASIA_MUSCAT => '+04:00',
            self::ASIA_NICOSIA => '+03:00', // 夏時間
            self::ASIA_NOVOKUZNETSK => '+07:00',
            self::ASIA_NOVOSIBIRSK => '+07:00',
            self::ASIA_OMSK => '+06:00',
            self::ASIA_ORAL => '+05:00',
            self::ASIA_PHNOM_PENH => '+07:00',
            self::ASIA_PONTIANAK => '+07:00',
            self::ASIA_PYONGYANG => '+08:30',
            self::ASIA_QATAR => '+03:00',
            self::ASIA_QYZYLORDA => '+05:00',
            self::ASIA_RIYADH => '+03:00',
            self::ASIA_SAIGON => '+07:00',
            self::ASIA_SAKHALIN => '+11:00',
            self::ASIA_SAMARKAND => '+05:00',
            self::ASIA_SEOUL => '+09:00',
            self::ASIA_SHANGHAI => '+08:00',
            self::ASIA_SINGAPORE => '+08:00',
            self::ASIA_SREDNEKOLYMSK => '+11:00',
            self::ASIA_TAIPEI => '+08:00',
            self::ASIA_TASHKENT => '+05:00',
            self::ASIA_TBILISI => '+04:00',
            self::ASIA_TEHRAN => '+04:30', // 夏時間
            self::ASIA_THIMPHU => '+06:00',
            self::ASIA_TOMSK => '+07:00',
            self::ASIA_ULAANBAATAR => '+08:00',
            self::ASIA_URUMQI => '+06:00',
            self::ASIA_UST_NERA => '+10:00',
            self::ASIA_VIENTIANE => '+07:00',
            self::ASIA_VLADIVOSTOK => '+10:00',
            self::ASIA_YAKUTSK => '+09:00',
            self::ASIA_YEKATERINBURG => '+05:00',
            self::ASIA_YEREVAN => '+04:00',
            self::ATLANTIC_AZORES => '-00:00', // 夏時間
            self::ATLANTIC_BERMUDA => '-03:00', // 夏時間
            self::ATLANTIC_CANARY => '+01:00', // 夏時間
            self::ATLANTIC_CAPE_VERDE => '-01:00',
            self::ATLANTIC_FAROE => '+01:00', // 夏時間
            self::ATLANTIC_MADEIRA => '+01:00', // 夏時間
            self::ATLANTIC_SOUTH_GEORGIA => '-02:00',
            self::ATLANTIC_STANLEY => '-03:00',
            self::AUSTRALIA_ADELAIDE => '+09:30', // 夏時間
            self::AUSTRALIA_BRISBANE => '+10:00',
            self::AUSTRALIA_BROKEN_HILL => '+09:30', // 夏時間
            self::AUSTRALIA_CANBERRA => '+10:00', // 夏時間
            self::AUSTRALIA_DARWIN => '+09:30',
            self::AUSTRALIA_EUCLA => '+08:45',
            self::AUSTRALIA_HOBART => '+10:00', // 夏時間
            self::AUSTRALIA_LHI => '+10:30', // 夏時間
            self::AUSTRALIA_LINDEMAN => '+10:00',
            self::AUSTRALIA_MELBOURNE => '+10:00', // 夏時間
            self::AUSTRALIA_PERTH => '+08:00',
            self::AUSTRALIA_SYDNEY => '+10:00', // 夏時間
            self::EUROPE_AMSTERDAM => '+02:00', // 夏時間
            self::EUROPE_ANDORRA => '+02:00', // 夏時間
            self::EUROPE_ASTRAKHAN => '+04:00',
            self::EUROPE_ATHENS => '+03:00', // 夏時間
            self::EUROPE_BELGRADE => '+02:00', // 夏時間
            self::EUROPE_BERLIN => '+02:00', // 夏時間
            self::EUROPE_BRATISLAVA => '+02:00', // 夏時間
            self::EUROPE_BRUSSELS => '+02:00', // 夏時間
            self::EUROPE_BUCHAREST => '+03:00', // 夏時間
            self::EUROPE_BUDAPEST => '+02:00', // 夏時間
            self::EUROPE_BUSYGINO => '+03:00',
            self::EUROPE_CHISINAU => '+03:00', // 夏時間
            self::EUROPE_COPENHAGEN => '+02:00', // 夏時間
            self::EUROPE_DUBLIN => '+01:00', // 夏時間
            self::EUROPE_GIBRALTAR => '+02:00', // 夏時間
            self::EUROPE_GUERNSEY => '+01:00', // 夏時間
            self::EUROPE_HELSINKI => '+03:00', // 夏時間
            self::EUROPE_ISLE_OF_MAN => '+01:00', // 夏時間
            self::EUROPE_ISTANBUL => '+03:00',
            self::EUROPE_JERSEY => '+01:00', // 夏時間
            self::EUROPE_KALININGRAD => '+02:00',
            self::EUROPE_KIEV => '+03:00', // 夏時間
            self::EUROPE_KIROV => '+03:00',
            self::EUROPE_LISBON => '+01:00', // 夏時間
            self::EUROPE_LJUBLJANA => '+02:00', // 夏時間
            self::EUROPE_LONDON => '+01:00', // 夏時間
            self::EUROPE_LUXEMBOURG => '+02:00', // 夏時間
            self::EUROPE_LYON => '+02:00', // 夏時間
            self::EUROPE_MADRID => '+02:00', // 夏時間
            self::EUROPE_MALTA => '+02:00', // 夏時間
            self::EUROPE_MARIEHAMN => '+03:00', // 夏時間
            self::EUROPE_MINSK => '+03:00',
            self::EUROPE_MONACO => '+02:00', // 夏時間
            self::EUROPE_MOSCOW => '+03:00',
            self::EUROPE_OSLO => '+02:00', // 夏時間
            self::EUROPE_PARIS => '+02:00', // 夏時間
            self::EUROPE_PODGORICA => '+02:00', // 夏時間
            self::EUROPE_PRAGUE => '+02:00', // 夏時間
            self::EUROPE_RIGA => '+03:00', // 夏時間
            self::EUROPE_ROME => '+02:00', // 夏時間
            self::EUROPE_SAMARA => '+04:00',
            self::EUROPE_SARAJEVO => '+02:00', // 夏時間
            self::EUROPE_SARATOV => '+04:00',
            self::EUROPE_SIMFEROPOL => '+03:00',
            self::EUROPE_SKOPJE => '+02:00', // 夏時間
            self::EUROPE_SOFIA => '+03:00', // 夏時間
            self::EUROPE_STOCKHOLM => '+02:00', // 夏時間
            self::EUROPE_TALLINN => '+03:00', // 夏時間
            self::EUROPE_TIRANE => '+02:00', // 夏時間
            self::EUROPE_ULYANOVSK => '+04:00',
            self::EUROPE_UZHGOROD => '+03:00', // 夏時間
            self::EUROPE_VADUZ => '+02:00', // 夏時間
            self::EUROPE_VATICAN => '+02:00', // 夏時間
            self::EUROPE_VIENNA => '+02:00', // 夏時間
            self::EUROPE_VILNIUS => '+03:00', // 夏時間
            self::EUROPE_VOLGOGRAD => '+03:00',
            self::EUROPE_WARSAW => '+02:00', // 夏時間
            self::EUROPE_ZAGREB => '+02:00', // 夏時間
            self::EUROPE_ZAPOROZHYE => '+03:00', // 夏時間
            self::INDIAN_ANTANANARIVO => '+03:00',
            self::INDIAN_CHAGOS => '+06:00',
            self::INDIAN_CHRISTMAS => '+07:00',
            self::INDIAN_COMORO => '+03:00',
            self::INDIAN_KERGUELEN => '+05:00',
            self::INDIAN_MAHE => '+04:00',
            self::INDIAN_MALDIVES => '+05:00',
            self::INDIAN_MAURITIUS => '+04:00',
            self::INDIAN_MAYOTTE => '+03:00',
            self::INDIAN_REUNION => '+04:00',
            self::PACIFIC_APIA => '+13:00',
            self::PACIFIC_AUCKLAND => '+12:00', // 夏時間
            self::PACIFIC_BOUGAINVILLE => '+11:00',
            self::PACIFIC_CHATHAM => '+12:45', // 夏時間
            self::PACIFIC_CHUUK => '+10:00',
            self::PACIFIC_EASTER => '-06:00',
            self::PACIFIC_EFATE => '+11:00',
            self::PACIFIC_FIJI => '+12:00',
            self::PACIFIC_FUNAFUTI => '+12:00',
            self::PACIFIC_GALAPAGOS => '-06:00',
            self::PACIFIC_GAMBIER => '-09:00',
            self::PACIFIC_GUADALCANAL => '+11:00',
            self::PACIFIC_GUAM => '+10:00',
            self::PACIFIC_HONOLULU => '-10:00',
            self::PACIFIC_JOHNSTON => '-10:00',
            self::PACIFIC_KIRITIMATI => '+14:00',
            self::PACIFIC_KOSRAE => '+11:00',
            self::PACIFIC_KWAJALEIN => '+12:00',
            self::PACIFIC_MAJURO => '+12:00',
            self::PACIFIC_MARQUESAS => '-09:30',
            self::PACIFIC_MIDWAY => '-11:00',
            self::PACIFIC_NAURU => '+12:00',
            self::PACIFIC_NIUE => '-11:00',
            self::PACIFIC_NORFOLK => '+11:00',
            self::PACIFIC_NOUMEA => '+11:00',
            self::PACIFIC_PAGO_PAGO => '-11:00',
            self::PACIFIC_PALAU => '+09:00',
            self::PACIFIC_PITCAIRN => '-08:00',
            self::PACIFIC_POHNPEI => '+11:00',
            self::PACIFIC_PORT_MORESBY => '+10:00',
            self::PACIFIC_RAROTONGA => '-10:00',
            self::PACIFIC_SAIPAN => '+10:00',
            self::PACIFIC_SAMOA => '+13:00',
            self::PACIFIC_TAHITI => '-10:00',
            self::PACIFIC_TARAWA => '+12:00',
            self::PACIFIC_TONGATAPU => '+13:00',
            self::PACIFIC_WAKE => '+12:00',
            self::PACIFIC_WALLIS => '+12:00',
        };
    }

    /**
     * 全てのタイムゾーンをvalue => labelの配列で取得
     */
    public static function options(): array
    {
        $options = [];
        foreach (self::cases() as $timezone) {
            $options[$timezone->value] = $timezone->label();
        }

        return $options;
    }
}
